# SPDX-FileCopyrightText: 2024 Ondsel <development@ondsel.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

FROM node:lts-alpine3.17

RUN npm install -g @feathersjs/cli

RUN apk update && \
    apk add zsh git vim zsh-autosuggestions zsh-syntax-highlighting bind-tools curl && \
    rm -rf /var/cache/apk/*

RUN sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

RUN echo "source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ~/.zshrc && \
echo "source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" >> ~/.zshrc

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy default uploads directory
COPY uploads/sample* ./uploads/
COPY uploads/public/branding ./uploads/public/branding
COPY uploads/public/sample* ./uploads/public/

ENV NODE_ENV development

EXPOSE 3030
# Attach to node process debug port
EXPOSE 9229

CMD [ "sh", "./entry.sh" ]
